<?php
/** @var $this Mage_Downloadable_Block_Sales_Order_Item_Renderer_Downloadable */
?>
<?php $item = $this->getItem() ?>
<?php if ($options = $this->getItemOptions()): ?>
    <div class="order-item item-options links">
        <?php foreach ($options as $option) : ?>
            <div>
                <span class="row-label mr-5"><?php echo trim($this->escapeHtml($option['label'])) ?>:</span>
                <?php if (!$this->getPrintStatus()): ?>
                    <?php $formatedOptionValue = $this->getFormatedOptionValue($option) ?>
                    <span class="row-value" <?php if (isset($formatedOptionValue['full_view'])): ?> class="wrapper"<?php endif; ?>>
                        <?php /* @escapeNotVerified */ echo trim($formatedOptionValue['value']) ?>
                        <?php if (isset($formatedOptionValue['full_view'])): ?>
                            <div class="content">
                                <div class="item options">
                                    <span class="row-label"><?php echo trim($this->escapeHtml($option['label'])) ?>:</span>
                                    <span class="row-value"><?php /* @escapeNotVerified */ echo trim($formatedOptionValue['full_view']) ?></span>
                                </div>
                            </div>
                        <?php endif; ?>
                    </span>
                <?php else: ?>
                    <span class="row-value">
                        <?php echo nl2br($this->escapeHtml((isset($option['print_value']) ? $option['print_value'] : $option['value']))) ?>
                    </span>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php /* downloadable */ ?>
<?php if ($links = $this->getLinks()): ?>
    <div class="order-item item-options links">
        <span class="row-label"><?php /* @escapeNotVerified */ echo $this->getLinksTitle() ?>:</span>
        <?php foreach ($links->getPurchasedItems() as $link): ?>
            <span class="content row-value"><?php echo trim($this->escapeHtml($link->getLinkTitle())); ?></span>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

